service:
  parser_db:
    container_name: parser_db
    image: postgres
    env_file: .env
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrations:
    build: .
    commmand: bash -c "python manage.py migrate && python manage.py loaddata fixture_transaction_types.json"
    depends_on:
      postgres_db:
        condition: service_healthy

  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      postgres_db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

volumes:
  pgdata:
