version: "3.9"

services:
  parser_db:
    container_name: parser_db
    image: postgres
    env_file: .env
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrations:
    build: .
    command: bash -c "while !</dev/tcp/parser_db/5432; do sleep 1; done; python manage.py migrate && python manage.py loaddata fixture_transaction_types.json"
    depends_on:
      parser_db:
        condition: service_healthy

  api:
    build: .
    env_file: .env
    command: bash -c "while !</dev/tcp/parser_db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      parser_db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - .:/app_cnab_parser

volumes:
  pgdata:
