# Generated by Django 4.1.5 on 2023-01-26 02:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('type', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('IN', 'inlet'), ('OUT', 'outlet')], max_length=7)),
                ('sign', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('cpf', models.CharField(max_length=11)),
                ('card', models.CharField(max_length=12)),
                ('time', models.TimeField()),
                ('store_owner', models.CharField(max_length=255)),
                ('store_name', models.CharField(max_length=255)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.transactiontype')),
            ],
        ),
    ]
